package com.github.rooneyandshadows.lightbulb.pickersdemo

import android.content.Context
import android.graphics.drawable.Drawable
import com.github.rooneyandshadows.lightbulb.application.activity.slidermenu.drawable.ShowMenuDrawable
import com.github.rooneyandshadows.lightbulb.dialogs.picker_dialog_chips.ChipsPickerAdapter


fun getShowMenuDrawable(context: Context): Drawable {
    return ShowMenuDrawable(context).apply {
        setEnabled(false)
    }
}

fun getMenuBackDrawable(context: Context): Drawable {
    return ShowMenuDrawable(context).apply {
        setEnabled(false)
        progress = 1F
    }
}


fun generateChips(): List<ChipsPickerAdapter.ChipModel> {
    val models: MutableList<ChipsPickerAdapter.ChipModel> = mutableListOf()
    models.add(ChipsPickerAdapter.ChipModel("Star"))
    models.add(ChipsPickerAdapter.ChipModel("Tag"))
    models.add(ChipsPickerAdapter.ChipModel("Search"))
    models.add(ChipsPickerAdapter.ChipModel("Block"))
    models.add(ChipsPickerAdapter.ChipModel("Center"))
    models.add(ChipsPickerAdapter.ChipModel("Right"))
    models.add(ChipsPickerAdapter.ChipModel("Cat"))
    models.add(ChipsPickerAdapter.ChipModel("Tree"))
    models.add(ChipsPickerAdapter.ChipModel("Person"))
    models.add(ChipsPickerAdapter.ChipModel("Generation"))
    models.add(ChipsPickerAdapter.ChipModel("Utility"))
    models.add(ChipsPickerAdapter.ChipModel("Category"))
    models.add(ChipsPickerAdapter.ChipModel("Label"))
    models.add(ChipsPickerAdapter.ChipModel("Side"))
    models.add(ChipsPickerAdapter.ChipModel("Section"))
    models.add(ChipsPickerAdapter.ChipModel("Page"))
    models.add(ChipsPickerAdapter.ChipModel("Class"))
    models.add(ChipsPickerAdapter.ChipModel("Type"))
    models.add(ChipsPickerAdapter.ChipModel("Performance"))
    models.add(ChipsPickerAdapter.ChipModel("Object"))
    models.add(ChipsPickerAdapter.ChipModel("Count"))
    models.add(ChipsPickerAdapter.ChipModel("Letter"))
    models.add(ChipsPickerAdapter.ChipModel("Subtitle"))
    models.add(ChipsPickerAdapter.ChipModel("Height"))
    models.add(ChipsPickerAdapter.ChipModel("Strenght"))
    models.add(ChipsPickerAdapter.ChipModel("Star"))
    models.add(ChipsPickerAdapter.ChipModel("Tag"))
    models.add(ChipsPickerAdapter.ChipModel("Search"))
    models.add(ChipsPickerAdapter.ChipModel("Block"))
    models.add(ChipsPickerAdapter.ChipModel("Center"))
    models.add(ChipsPickerAdapter.ChipModel("Right"))
    models.add(ChipsPickerAdapter.ChipModel("Cat"))
    models.add(ChipsPickerAdapter.ChipModel("Tree"))
    models.add(ChipsPickerAdapter.ChipModel("Person"))
    models.add(ChipsPickerAdapter.ChipModel("Generation"))
    models.add(ChipsPickerAdapter.ChipModel("Utility"))
    models.add(ChipsPickerAdapter.ChipModel("Category"))
    models.add(ChipsPickerAdapter.ChipModel("Label"))
    models.add(ChipsPickerAdapter.ChipModel("Side"))
    models.add(ChipsPickerAdapter.ChipModel("Section"))
    models.add(ChipsPickerAdapter.ChipModel("Page"))
    models.add(ChipsPickerAdapter.ChipModel("Class"))
    models.add(ChipsPickerAdapter.ChipModel("Type"))
    models.add(ChipsPickerAdapter.ChipModel("Performance"))
    models.add(ChipsPickerAdapter.ChipModel("Object"))
    models.add(ChipsPickerAdapter.ChipModel("Count"))
    models.add(ChipsPickerAdapter.ChipModel("Letter"))
    models.add(ChipsPickerAdapter.ChipModel("Subtitle"))
    models.add(ChipsPickerAdapter.ChipModel("Height"))
    models.add(ChipsPickerAdapter.ChipModel("Strenght"))
    models.add(ChipsPickerAdapter.ChipModel("Star"))
    models.add(ChipsPickerAdapter.ChipModel("Tag"))
    models.add(ChipsPickerAdapter.ChipModel("Search"))
    models.add(ChipsPickerAdapter.ChipModel("Block"))
    models.add(ChipsPickerAdapter.ChipModel("Center"))
    models.add(ChipsPickerAdapter.ChipModel("Right"))
    models.add(ChipsPickerAdapter.ChipModel("Cat"))
    models.add(ChipsPickerAdapter.ChipModel("Tree"))
    models.add(ChipsPickerAdapter.ChipModel("Person"))
    models.add(ChipsPickerAdapter.ChipModel("Generation"))
    models.add(ChipsPickerAdapter.ChipModel("Utility"))
    models.add(ChipsPickerAdapter.ChipModel("Category"))
    models.add(ChipsPickerAdapter.ChipModel("Label"))
    models.add(ChipsPickerAdapter.ChipModel("Side"))
    models.add(ChipsPickerAdapter.ChipModel("Section"))
    models.add(ChipsPickerAdapter.ChipModel("Page"))
    models.add(ChipsPickerAdapter.ChipModel("Class"))
    models.add(ChipsPickerAdapter.ChipModel("Type"))
    models.add(ChipsPickerAdapter.ChipModel("Performance"))
    models.add(ChipsPickerAdapter.ChipModel("Object"))
    models.add(ChipsPickerAdapter.ChipModel("Count"))
    models.add(ChipsPickerAdapter.ChipModel("Letter"))
    models.add(ChipsPickerAdapter.ChipModel("Subtitle"))
    models.add(ChipsPickerAdapter.ChipModel("Height"))
    models.add(ChipsPickerAdapter.ChipModel("Strenght"))
    models.add(ChipsPickerAdapter.ChipModel("Star"))
    models.add(ChipsPickerAdapter.ChipModel("Tag"))
    models.add(ChipsPickerAdapter.ChipModel("Search"))
    models.add(ChipsPickerAdapter.ChipModel("Block"))
    models.add(ChipsPickerAdapter.ChipModel("Center"))
    models.add(ChipsPickerAdapter.ChipModel("Right"))
    models.add(ChipsPickerAdapter.ChipModel("Cat"))
    models.add(ChipsPickerAdapter.ChipModel("Tree"))
    models.add(ChipsPickerAdapter.ChipModel("Person"))
    models.add(ChipsPickerAdapter.ChipModel("Generation"))
    models.add(ChipsPickerAdapter.ChipModel("Utility"))
    models.add(ChipsPickerAdapter.ChipModel("Category"))
    models.add(ChipsPickerAdapter.ChipModel("Label"))
    models.add(ChipsPickerAdapter.ChipModel("Side"))
    models.add(ChipsPickerAdapter.ChipModel("Section"))
    models.add(ChipsPickerAdapter.ChipModel("Page"))
    models.add(ChipsPickerAdapter.ChipModel("Class"))
    models.add(ChipsPickerAdapter.ChipModel("Type"))
    models.add(ChipsPickerAdapter.ChipModel("Performance"))
    models.add(ChipsPickerAdapter.ChipModel("Object"))
    models.add(ChipsPickerAdapter.ChipModel("Count"))
    models.add(ChipsPickerAdapter.ChipModel("Letter"))
    models.add(ChipsPickerAdapter.ChipModel("Subtitle"))
    models.add(ChipsPickerAdapter.ChipModel("Height"))
    models.add(ChipsPickerAdapter.ChipModel("Strenght"))
    models.add(ChipsPickerAdapter.ChipModel("Star"))
    models.add(ChipsPickerAdapter.ChipModel("Tag"))
    models.add(ChipsPickerAdapter.ChipModel("Search"))
    models.add(ChipsPickerAdapter.ChipModel("Block"))
    models.add(ChipsPickerAdapter.ChipModel("Center"))
    models.add(ChipsPickerAdapter.ChipModel("Right"))
    models.add(ChipsPickerAdapter.ChipModel("Cat"))
    models.add(ChipsPickerAdapter.ChipModel("Tree"))
    models.add(ChipsPickerAdapter.ChipModel("Person"))
    models.add(ChipsPickerAdapter.ChipModel("Generation"))
    models.add(ChipsPickerAdapter.ChipModel("Utility"))
    models.add(ChipsPickerAdapter.ChipModel("Category"))
    models.add(ChipsPickerAdapter.ChipModel("Label"))
    models.add(ChipsPickerAdapter.ChipModel("Side"))
    models.add(ChipsPickerAdapter.ChipModel("Section"))
    models.add(ChipsPickerAdapter.ChipModel("Page"))
    models.add(ChipsPickerAdapter.ChipModel("Class"))
    models.add(ChipsPickerAdapter.ChipModel("Type"))
    models.add(ChipsPickerAdapter.ChipModel("Performance"))
    models.add(ChipsPickerAdapter.ChipModel("Object"))
    models.add(ChipsPickerAdapter.ChipModel("Count"))
    models.add(ChipsPickerAdapter.ChipModel("Letter"))
    models.add(ChipsPickerAdapter.ChipModel("Subtitle"))
    models.add(ChipsPickerAdapter.ChipModel("Height"))
    models.add(ChipsPickerAdapter.ChipModel("Strenght"))
    return models
}

